apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: archon-orchestrator

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/part-of: archon
  app.kubernetes.io/component: orchestrator
