apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: archon-model-server

resources:
  # Constraints
  - resource-quota.yaml
  - limit-range.yaml
  # Configuration
  - configmap.yaml
  # Storage
  - pvc.yaml
  # Workloads
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: archon
  app.kubernetes.io/component: model-server
