apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpu-quota
  namespace: archon-system
  labels:
    app.kubernetes.io/name: gpu-quota
    app.kubernetes.io/part-of: archon
    app.kubernetes.io/component: model-server
spec:
  hard:
    requests.nvidia.com/gpu: "1"
    limits.nvidia.com/gpu: "1"
