apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpu-quota
  namespace: archon-model-server
  labels:
    app.kubernetes.io/name: gpu-quota
    app.kubernetes.io/part-of: archon
    app.kubernetes.io/component: model-server
spec:
  hard:
    requests.nvidia.com/gpu: "1"
    limits.nvidia.com/gpu: "1"
    requests.memory: "32Gi"
    limits.memory: "48Gi"
    requests.cpu: "16"
    limits.cpu: "32"
