apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- secrets.yaml
- services.yaml
- qdrant-statefulset.yaml
- postgres-statefulset.yaml
- query-deployment.yaml
- monitor-cronjob.yaml
- ingress.yaml
- init-job.yaml

namespace: archon

generatorOptions:
  disableNameSuffixHash: true
